FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY apps/event ./apps/event
COPY libs ./libs

COPY . .
COPY .env .env

RUN npm install
RUN npm run build event

RUN npm install -g pm2

EXPOSE 3002

CMD ["pm2-runtime", "start", "dist/apps/event/main.js"]