FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

COPY apps/gateway ./apps/gateway
COPY apps/auth ./apps/auth
COPY apps/event ./apps/event

COPY libs ./libs

COPY . .
COPY .env .env

RUN npm install
RUN npm run build gateway

RUN npm install -g pm2

EXPOSE 3000

CMD ["pm2-runtime", "start", "dist/apps/gateway/main.js"]